spring.application.name=blockchain-api

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# DataSource
spring.datasource.url=jdbc:h2:file:./blockchain-db
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# BlockchainApi
validator.zeros=5
# Value of number of threads (multi-thread-miner.num-of-threads) will be ignored,
# if miner type (miner-type) is set to be single thread
miner-type=java_api_multi_thread
multi-thread-miner.num-of-threads=4