spring.application.name=blockchain-api-example

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# DataSource
spring.datasource.url=jdbc:h2:file:./product-blockchain-db
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# BlockchainApi
blockchain-api.core.validator-zeros=5
blockchain-api.core.miner-type=java_api_multi_thread_v2
blockchain-api.core.multi-thread-miner-num-of-threads=4